[package]
name = "biodivine-lib-bma-data"
version = "0.0.1"
authors = ["Ondřej Huvar <xhuvar@fi.muni.cz>", "Samuel Pastva <sam.pastva@gmail.com>"]
edition = "2021"
description = "Library for working with models in BMA format."
homepage = "https://github.com/sybila/biodivine-lib-bma-data"
repository = "https://github.com/sybila/biodivine-lib-bma-data"
readme = "README.md"
keywords = ["boolean-network", "BMA", "systems-biology"]
categories = ["science", "simulation"]
license = "MIT"

[lib]
name = "biodivine_lib_bma_data"
path = "src/lib.rs"

[[bin]]
name = "load-json"
path = "src/bin/load_json.rs"

[[bin]]
name = "load-xml"
path = "src/bin/load_xml.rs"

[dependencies]
biodivine-lib-param-bn = ">=0.5.11, <1.0.0"
clap = { version = "4.1.4", features = ["derive"] }
rand = "0.8.5"
regex = "1.10.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.6.0"
num-rational = "0.4.2"
